"""Auto-generated hard-wired GEMM analytical model."""
SOURCE_XLSX = 'C:\\Users\\cli17\\source\\repos\\GEMM analytical model\\example.xlsx'
SOURCE_SHEET = 'summary wo L2 fwd (baseline)'

import argparse
import ast
import csv
import sys
import re

import math


def CEILING(x, significance=1):
    """Excel CEILING: round up to nearest multiple of significance."""
    if significance == 0:
        return 0
    return math.ceil(x / significance) * significance


def FLOOR(x, significance=1):
    """Excel FLOOR: round down to nearest multiple of significance."""
    if significance == 0:
        return 0
    return math.floor(x / significance) * significance


def IF(condition, true_val, false_val):
    """Excel IF."""
    return true_val if condition else false_val


MIN = min
MAX = max

DATA_FORMAT_TO_BYTES = {
    'fp4': 0.5,
    'i4': 0.5,
    'mxfp4': 0.53125,
    'nvfp4_4x': 0.5625,
    'nvfp4_6x': 0.5625,
    'fp6': 0.75,
    'mxfp6': 0.78125,
    'fp8': 1,
    'i8': 1,
    'mxfp8': 1.03125,
    'mxi8': 1.03125,
    'fp16': 2,
    'tf32': 4,
}

def _load_params_csv(path: str, expected_names: list, file_label: str, all_known_names: set) -> dict:
    """Load and strictly validate a parameter CSV file (Name,Value[,Label] columns)."""
    params: dict = {}
    expected_set = set(expected_names)
    with open(path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = row['Name'].strip()
            value_str = row['Value'].strip()
            if name not in expected_set:
                if name in all_known_names:
                    sys.exit(f"Error: '{name}' is not a {file_label} parameter (wrong file: {path})")
                else:
                    sys.exit(f"Error: Unknown parameter '{name}' in {path}")
            try:
                v = float(value_str)
                v = int(v) if v == int(v) else v
            except (ValueError, OverflowError):
                v = value_str
            params[name] = v
    missing = expected_set - set(params)
    if missing:
        sys.exit(f"Error: Missing required {file_label} parameters in '{path}': {sorted(missing)}")
    return params

def compute_core_values(workload_params: dict, machine_params: dict) -> dict:
    """Compute all model variables and return them as a dict."""
    # Validate format keys are valid DATA_FORMAT_TO_BYTES keys
    for _fmt_key in FORMAT_KEY_NAMES:
        _fmt_val = workload_params[_fmt_key]
        if _fmt_val not in DATA_FORMAT_TO_BYTES:
            sys.exit(f"Error: format key '{_fmt_key}' value '{_fmt_val}' not in DATA_FORMAT_TO_BYTES: {sorted(DATA_FORMAT_TO_BYTES)}")

    # === Section 1: Machine Pre-Defined Parameters ===

    # row 8 | GT Freq (GHz)
    GT_FREQ_GHZ = machine_params['GT_FREQ_GHZ']

    # row 26 | XeCU count
    XECU_COUNT = machine_params['XECU_COUNT']

    # row 27 | XeCore per XeCU
    XECORE_PER_XECU = machine_params['XECORE_PER_XECU']

    # row 28 | EU per XeCore
    EU_PER_XECORE = machine_params['EU_PER_XECORE']

    # row 29 | L2 banks per XeCU
    L2_BANKS_PER_XECU = machine_params['L2_BANKS_PER_XECU']

    # row 30 | bank capacity (MB)
    BANK_CAPACITY_MB = machine_params['BANK_CAPACITY_MB']

    # row 32 | DPAS depth
    DPAS_DEPTH = machine_params['DPAS_DEPTH']

    # row 35 | compute Efficiency %
    COMPUTE_EFFICIENCY_PCT = machine_params['COMPUTE_EFFICIENCY_PCT']

    # row 86 | L1 read max (B/EU/clk)
    L1_READ_MAX_B_EU_CLK = machine_params['L1_READ_MAX_B_EU_CLK']

    # row 87 | L1 write max (B/EU/clk)
    L1_WRITE_MAX_B_EU_CLK = machine_params['L1_WRITE_MAX_B_EU_CLK']

    # row 97 | GTI Read max BW (B/clk)
    GTI_READ_MAX_BW_B_CLK = machine_params['GTI_READ_MAX_BW_B_CLK']

    # row 98 | GTI Write max BW(B/clk)
    GTI_WRITE_MAX_BW_B_CLK = machine_params['GTI_WRITE_MAX_BW_B_CLK']

    # row 124 | max possible HBM BW (GB/s)
    MAX_POSSIBLE_HBM_BW_GB_S = machine_params['MAX_POSSIBLE_HBM_BW_GB_S']

    # === Section 2: Workload Pre-Defined Parameters ===

    # row 3 | fp8
    INPUT_A_DATA_FORMAT = workload_params['INPUT_A_DATA_FORMAT']

    # row 4 | fp4
    INPUT_B_DATA_FORMAT = workload_params['INPUT_B_DATA_FORMAT']

    # row 5 | fp8
    OUTPUT_D_DATA_FORMAT = workload_params['OUTPUT_D_DATA_FORMAT']

    # row 9 | M
    M = workload_params['M']

    # row 10 | K
    K = workload_params['K']

    # row 11 | N
    N = workload_params['N']

    # row 24 | output bytes per element , fp32
    OUTPUT_BYTES_PER_ELEMENT_FP32 = workload_params['OUTPUT_BYTES_PER_ELEMENT_FP32']

    # row 34 | Machine occupancy %
    MACHINE_OCCUPANCY_PCT = workload_params['MACHINE_OCCUPANCY_PCT']

    # row 39 | M per thread
    M_PER_THREAD = workload_params['M_PER_THREAD']

    # row 40 | K per thread
    K_PER_THREAD = workload_params['K_PER_THREAD']

    # row 41 | N per thread
    N_PER_THREAD = workload_params['N_PER_THREAD']

    # row 45 | TG width in units of thread
    TG_WIDTH_IN_UNITS_OF_THREAD = workload_params['TG_WIDTH_IN_UNITS_OF_THREAD']

    # row 46 | TG height in units of thread
    TG_HEIGHT_IN_UNITS_OF_THREAD = workload_params['TG_HEIGHT_IN_UNITS_OF_THREAD']

    # row 50 | XeCore cluster width in units of TG. Keep the cluster size as 4.
    XECORE_CLUSTER_WIDTH_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4 = workload_params['XECORE_CLUSTER_WIDTH_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4']

    # row 51 | XeCore cluster height in units of TG. Keep the cluster size as 4.
    XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4 = workload_params['XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4']

    # row 54 | XeCU tile width in units of TG
    XECU_TILE_WIDTH_IN_UNITS_OF_TG = workload_params['XECU_TILE_WIDTH_IN_UNITS_OF_TG']

    # row 55 | XeCU tile height in units of TG
    XECU_TILE_HEIGHT_IN_UNITS_OF_TG = workload_params['XECU_TILE_HEIGHT_IN_UNITS_OF_TG']

    # row 58 | GPU tile width in XeCU unit
    GPU_TILE_WIDTH_IN_XECU_UNIT = workload_params['GPU_TILE_WIDTH_IN_XECU_UNIT']

    # === Section 3: Machine & Workload Derived Parameters ===

    # row 22 | input A bytes per element
    INPUT_A_BYTES_PER_ELEMENT = DATA_FORMAT_TO_BYTES[INPUT_A_DATA_FORMAT]

    # row 23 | input B bytes per element
    INPUT_B_BYTES_PER_ELEMENT = DATA_FORMAT_TO_BYTES[INPUT_B_DATA_FORMAT]

    # row 25 | output bytes per element after down conversion
    OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION = DATA_FORMAT_TO_BYTES[OUTPUT_D_DATA_FORMAT]

    # row 33 | EU count
    EU_COUNT = XECORE_PER_XECU * EU_PER_XECORE * XECU_COUNT

    # row 36 | MMA MAC throughput per Xecore
    MMA_MAC_THROUGHPUT_PER_XECORE = (
        MIN(4 / (FLOOR(INPUT_A_BYTES_PER_ELEMENT * 2, 1) / 2), 4 / (FLOOR(INPUT_B_BYTES_PER_ELEMENT * 2,
        1) / 2)) * DPAS_DEPTH * 16 * EU_PER_XECORE
    )

    # row 42 | clks per DPAS
    CLKS_PER_DPAS = M_PER_THREAD * K_PER_THREAD * N_PER_THREAD / (MMA_MAC_THROUGHPUT_PER_XECORE / EU_PER_XECORE)

    # row 43 | thread width in units of elements
    THREAD_WIDTH_IN_UNITS_OF_ELEMENTS = N_PER_THREAD

    # row 44 | thread height in units of elements
    THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS = M_PER_THREAD

    # row 47 | TG width in units of element (realized by multiple MMA iterations)
    TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS = TG_WIDTH_IN_UNITS_OF_THREAD * THREAD_WIDTH_IN_UNITS_OF_ELEMENTS

    # row 14 | TG tiles in N
    TG_TILES_IN_N = N / TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS

    # row 48 | TG height in units of element
    TG_HEIGHT_IN_UNITS_OF_ELEMENT = TG_HEIGHT_IN_UNITS_OF_THREAD * THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS

    # row 15 | TG tiles in M
    TG_TILES_IN_M = M / TG_HEIGHT_IN_UNITS_OF_ELEMENT

    # row 52 | XeCore cluster width in units of element
    XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT = (
        XECORE_CLUSTER_WIDTH_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4 *
        TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS
    )

    # row 16 | TG cluster tiles in N
    TG_CLUSTER_TILES_IN_N = N / XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT

    # row 53 | XeCore cluster height in units of element
    XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT = XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4 * TG_HEIGHT_IN_UNITS_OF_ELEMENT

    # row 17 | TG cluster tiles in M
    TG_CLUSTER_TILES_IN_M = M / XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT

    # row 56 | XeCU tile width in units of element
    XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT = (
        XECU_TILE_WIDTH_IN_UNITS_OF_TG *
        TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS
    )

    # row 18 | XeCU tiles in N
    XECU_TILES_IN_N = N / XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT

    # row 20 | GPU tiles in N
    GPU_TILES_IN_N = N / XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT / GPU_TILE_WIDTH_IN_XECU_UNIT

    # row 57 | XeCU tile height in units of element
    XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT = XECU_TILE_HEIGHT_IN_UNITS_OF_TG * TG_HEIGHT_IN_UNITS_OF_ELEMENT

    # row 19 | XeCU tiles in M
    XECU_TILES_IN_M = M / XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT

    # row 59 | GPU tile height in XeCU uint
    GPU_TILE_HEIGHT_IN_XECU_UINT = XECU_COUNT / GPU_TILE_WIDTH_IN_XECU_UNIT

    # row 21 | GPU tiles in M
    GPU_TILES_IN_M = M / XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT / GPU_TILE_HEIGHT_IN_XECU_UINT

    # row 13 | waves
    WAVES = CEILING(GPU_TILES_IN_N, 1) * CEILING(GPU_TILES_IN_M, 1)

    # row 60 | GPU tile width in units of elemetns
    GPU_TILE_WIDTH_IN_UNITS_OF_ELEMETNS = GPU_TILE_WIDTH_IN_XECU_UNIT * XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT

    # row 61 | GPU tile height in units of elemetns
    GPU_TILE_HEIGHT_IN_UNITS_OF_ELEMETNS = GPU_TILE_HEIGHT_IN_XECU_UINT * XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT

    # row 63 | Mat A input size (B)
    MAT_A_INPUT_SIZE_B = M * K * INPUT_A_BYTES_PER_ELEMENT

    # row 64 | Mat B input size (B)
    MAT_B_INPUT_SIZE_B = K * N * INPUT_B_BYTES_PER_ELEMENT

    # row 65 | Mat C input & D output size (B)
    MAT_C_INPUT_D_OUTPUT_SIZE_B = M * N * OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION

    # row 66 | Mat D intermediate size (B)
    MAT_D_INTERMEDIATE_SIZE_B = M * N * OUTPUT_BYTES_PER_ELEMENT_FP32

    # row 102 | Total L2 size (B) for a single instance
    TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE = BANK_CAPACITY_MB * L2_BANKS_PER_XECU * 1024 * 1024

    # [row 103] Working data set size of K in L2
    #           (corresponds to 20K clocks of thread divergence)
    WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE = MIN(20000 * (K_PER_THREAD / CLKS_PER_DPAS), K)

    # [row 104] Total required L2 size for ideal hit rate (B)
    #           for a single instance and single wave
    TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE = (
        (XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT * INPUT_A_BYTES_PER_ELEMENT *
        WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE) +
        (XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT * INPUT_B_BYTES_PER_ELEMENT *
        WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE) +
        (XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT * XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT *
        OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION)
    )

    # row 125 | max possible HBM BW  @  freq (B/clk)
    MAX_POSSIBLE_HBM_BW_FREQ_B_CLK = MAX_POSSIBLE_HBM_BW_GB_S / GT_FREQ_GHZ

    # === Section 4: Machine Stats ===

    # row 37 | clk  @  specified efficiency
    CLK_SPECIFIED_EFFICIENCY = (
        M * K * N / XECORE_PER_XECU / XECU_COUNT / MMA_MAC_THROUGHPUT_PER_XECORE /
        COMPUTE_EFFICIENCY_PCT
    )

    # row 69 | Total L2 read (B)
    TOTAL_L2_READ_B = (
        (MAT_A_INPUT_SIZE_B * CEILING(N /
        TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS, 1) + MAT_B_INPUT_SIZE_B *
        CEILING(M / TG_HEIGHT_IN_UNITS_OF_ELEMENT, 1))
    )

    # row 70 | Total L2 write (B)
    TOTAL_L2_WRITE_B = MAT_C_INPUT_D_OUTPUT_SIZE_B

    # row 71 | Total L1 read (B)
    TOTAL_L1_READ_B = (
        (MAT_A_INPUT_SIZE_B * CEILING(N / THREAD_WIDTH_IN_UNITS_OF_ELEMENTS, 1) + MAT_B_INPUT_SIZE_B *
        CEILING(M / THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS, 1))
    )

    # row 72 | Total L1 write (B)
    TOTAL_L1_WRITE_B = MAT_C_INPUT_D_OUTPUT_SIZE_B

    # row 74 | L2 read (B/XeCore/clk)
    L2_READ_B_XECORE_CLK = TOTAL_L2_READ_B / (XECU_COUNT * XECORE_PER_XECU) / CLK_SPECIFIED_EFFICIENCY

    # row 75 | L2 write (B/XeCore/clk)
    L2_WRITE_B_XECORE_CLK = TOTAL_L2_WRITE_B / (XECU_COUNT * XECORE_PER_XECU) / CLK_SPECIFIED_EFFICIENCY

    # row 76 | L2 read + write (B/XeCore/clk)
    L2_READ_WRITE_B_XECORE_CLK = L2_READ_B_XECORE_CLK + L2_WRITE_B_XECORE_CLK

    # row 79 | L1 read (B/EU/clk)
    L1_READ_B_EU_CLK = TOTAL_L1_READ_B / (EU_COUNT) / CLK_SPECIFIED_EFFICIENCY

    # row 77 | L1 read (B/XeCore/clk)
    L1_READ_B_XECORE_CLK = L1_READ_B_EU_CLK * EU_PER_XECORE

    # row 80 | L1 write (B/EU/clk)
    L1_WRITE_B_EU_CLK = TOTAL_L1_WRITE_B / (EU_COUNT) / CLK_SPECIFIED_EFFICIENCY

    # row 78 | L1 write (B/XeCoreclk)
    L1_WRITE_B_XECORECLK = L1_WRITE_B_EU_CLK * EU_PER_XECORE

    # row 83 | L2 read max (B/XeCore/clk)
    L2_READ_MAX_B_XECORE_CLK = XECORE_PER_XECU * 64 / XECORE_PER_XECU

    # row 84 | L2 write max (B/XeCore/clk)
    L2_WRITE_MAX_B_XECORE_CLK = L2_READ_MAX_B_XECORE_CLK

    # row 85 | L2 read + write max (B/XeCore/clk)
    L2_READ_WRITE_MAX_B_XECORE_CLK = L2_WRITE_MAX_B_XECORE_CLK

    # row 90 | L2 read (B/XeCore/clk) %
    L2_READ_B_XECORE_CLK_PCT = L2_READ_B_XECORE_CLK / L2_READ_MAX_B_XECORE_CLK

    # row 91 | L2 write (B/XeCore/clk) %
    L2_WRITE_B_XECORE_CLK_PCT = L2_WRITE_B_XECORE_CLK / L2_WRITE_MAX_B_XECORE_CLK

    # row 92 | L2 read + write (B/XeCore/clk) %
    L2_READ_WRITE_B_XECORE_CLK_PCT = L2_READ_WRITE_B_XECORE_CLK / L2_READ_WRITE_MAX_B_XECORE_CLK

    # row 93 | L1 read (B/EU/clk) %
    L1_READ_B_EU_CLK_PCT = L1_READ_B_EU_CLK / L1_READ_MAX_B_EU_CLK

    # row 94 | L1 write (B/EU/clk) %
    L1_WRITE_B_EU_CLK_PCT = L1_WRITE_B_EU_CLK / L1_WRITE_MAX_B_EU_CLK

    # row 106 | L2 hit rate (assumed random access within the working data set) %
    L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT = (
        MIN(TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE /
        TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE, 1)
    )

    # row 107 | L2 miss rate %
    L2_MISS_RATE_PCT = 1 - L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT

    # row 108 | Total L2 read traffic (B)
    TOTAL_L2_READ_TRAFFIC_B = TOTAL_L2_READ_B

    # [row 110] Probability of matA hit in L2 during a non-first wave (%)
    PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT = (
        IF(MAT_A_INPUT_SIZE_B + MAT_B_INPUT_SIZE_B + MAT_C_INPUT_D_OUTPUT_SIZE_B <=
        TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE, 1.0, IF(K > 2 *
        WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE, 0.0, 1 - (K -
        WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE) /
        WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE))
    )

    # [row 111] Probability of matB hit in L2 during a non-first wave (%)
    PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT = (
        IF(MAT_A_INPUT_SIZE_B + MAT_B_INPUT_SIZE_B + MAT_C_INPUT_D_OUTPUT_SIZE_B <=
        TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE, 1.0, 0.0)
    )

    # [row 112] Probability of matA miss in L2 during a non-first wave (%)
    PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT = 1 - PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT

    # [row 113] Probability of matB miss in L2 during a non-first wave (%)
    PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT = 1 - PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT

    # [row 116] Total HBM read (B) after completion of a wave
    #           (cold-cache assumption)
    TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE = (
        (MAT_A_INPUT_SIZE_B + MAT_A_INPUT_SIZE_B * (CEILING(N / XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT, 1)
        - 1) * PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT + MAT_B_INPUT_SIZE_B +
        MAT_B_INPUT_SIZE_B * (CEILING(M / XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT, 1) - 1) *
        PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT + (TOTAL_L2_READ_TRAFFIC_B -
        (MAT_A_INPUT_SIZE_B + MAT_A_INPUT_SIZE_B * (CEILING(N / XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT, 1)
        - 1) * PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT + MAT_B_INPUT_SIZE_B +
        MAT_B_INPUT_SIZE_B * (CEILING(M / XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT, 1) - 1) *
        PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT)) * L2_MISS_RATE_PCT) / 2
    )

    # row 117 | Total HBM write (B)
    TOTAL_HBM_WRITE_B = MAT_C_INPUT_D_OUTPUT_SIZE_B

    # row 118 | Total HBM (B)
    TOTAL_HBM_B = TOTAL_HBM_WRITE_B + TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE

    # row 121 | HBM read (B/clk)
    HBM_READ_B_CLK = TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE / CLK_SPECIFIED_EFFICIENCY

    # row 122 | HBM write (B/clk)
    HBM_WRITE_B_CLK = TOTAL_HBM_WRITE_B / CLK_SPECIFIED_EFFICIENCY

    # row 123 | HBM total (B/clk)
    HBM_TOTAL_B_CLK = TOTAL_HBM_B / CLK_SPECIFIED_EFFICIENCY

    # row 126 | HBM BW (%)
    HBM_BW_PCT = HBM_TOTAL_B_CLK / MAX_POSSIBLE_HBM_BW_FREQ_B_CLK

    # row 127 | GTI read BW (%)
    GTI_READ_BW_PCT = HBM_READ_B_CLK / GTI_READ_MAX_BW_B_CLK

    # row 128 | GTI write BW (%)
    GTI_WRITE_BW_PCT = HBM_WRITE_B_CLK / GTI_WRITE_MAX_BW_B_CLK

    return {
        'INPUT_A_DATA_FORMAT': INPUT_A_DATA_FORMAT,
        'INPUT_B_DATA_FORMAT': INPUT_B_DATA_FORMAT,
        'OUTPUT_D_DATA_FORMAT': OUTPUT_D_DATA_FORMAT,
        'M': M,
        'K': K,
        'N': N,
        'OUTPUT_BYTES_PER_ELEMENT_FP32': OUTPUT_BYTES_PER_ELEMENT_FP32,
        'MACHINE_OCCUPANCY_PCT': MACHINE_OCCUPANCY_PCT,
        'M_PER_THREAD': M_PER_THREAD,
        'K_PER_THREAD': K_PER_THREAD,
        'N_PER_THREAD': N_PER_THREAD,
        'TG_WIDTH_IN_UNITS_OF_THREAD': TG_WIDTH_IN_UNITS_OF_THREAD,
        'TG_HEIGHT_IN_UNITS_OF_THREAD': TG_HEIGHT_IN_UNITS_OF_THREAD,
        'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4': XECORE_CLUSTER_WIDTH_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4,
        'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4': XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4,
        'XECU_TILE_WIDTH_IN_UNITS_OF_TG': XECU_TILE_WIDTH_IN_UNITS_OF_TG,
        'XECU_TILE_HEIGHT_IN_UNITS_OF_TG': XECU_TILE_HEIGHT_IN_UNITS_OF_TG,
        'GPU_TILE_WIDTH_IN_XECU_UNIT': GPU_TILE_WIDTH_IN_XECU_UNIT,
        'GT_FREQ_GHZ': GT_FREQ_GHZ,
        'XECU_COUNT': XECU_COUNT,
        'XECORE_PER_XECU': XECORE_PER_XECU,
        'EU_PER_XECORE': EU_PER_XECORE,
        'L2_BANKS_PER_XECU': L2_BANKS_PER_XECU,
        'BANK_CAPACITY_MB': BANK_CAPACITY_MB,
        'DPAS_DEPTH': DPAS_DEPTH,
        'COMPUTE_EFFICIENCY_PCT': COMPUTE_EFFICIENCY_PCT,
        'L1_READ_MAX_B_EU_CLK': L1_READ_MAX_B_EU_CLK,
        'L1_WRITE_MAX_B_EU_CLK': L1_WRITE_MAX_B_EU_CLK,
        'GTI_READ_MAX_BW_B_CLK': GTI_READ_MAX_BW_B_CLK,
        'GTI_WRITE_MAX_BW_B_CLK': GTI_WRITE_MAX_BW_B_CLK,
        'MAX_POSSIBLE_HBM_BW_GB_S': MAX_POSSIBLE_HBM_BW_GB_S,
        'INPUT_A_BYTES_PER_ELEMENT': INPUT_A_BYTES_PER_ELEMENT,
        'INPUT_B_BYTES_PER_ELEMENT': INPUT_B_BYTES_PER_ELEMENT,
        'OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION': OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION,
        'EU_COUNT': EU_COUNT,
        'MMA_MAC_THROUGHPUT_PER_XECORE': MMA_MAC_THROUGHPUT_PER_XECORE,
        'CLK_SPECIFIED_EFFICIENCY': CLK_SPECIFIED_EFFICIENCY,
        'CLKS_PER_DPAS': CLKS_PER_DPAS,
        'THREAD_WIDTH_IN_UNITS_OF_ELEMENTS': THREAD_WIDTH_IN_UNITS_OF_ELEMENTS,
        'THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS': THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS,
        'TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS': TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS,
        'TG_TILES_IN_N': TG_TILES_IN_N,
        'TG_HEIGHT_IN_UNITS_OF_ELEMENT': TG_HEIGHT_IN_UNITS_OF_ELEMENT,
        'TG_TILES_IN_M': TG_TILES_IN_M,
        'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT': XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT,
        'TG_CLUSTER_TILES_IN_N': TG_CLUSTER_TILES_IN_N,
        'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT': XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT,
        'TG_CLUSTER_TILES_IN_M': TG_CLUSTER_TILES_IN_M,
        'XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT': XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT,
        'XECU_TILES_IN_N': XECU_TILES_IN_N,
        'GPU_TILES_IN_N': GPU_TILES_IN_N,
        'XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT': XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT,
        'XECU_TILES_IN_M': XECU_TILES_IN_M,
        'GPU_TILE_HEIGHT_IN_XECU_UINT': GPU_TILE_HEIGHT_IN_XECU_UINT,
        'GPU_TILES_IN_M': GPU_TILES_IN_M,
        'WAVES': WAVES,
        'GPU_TILE_WIDTH_IN_UNITS_OF_ELEMETNS': GPU_TILE_WIDTH_IN_UNITS_OF_ELEMETNS,
        'GPU_TILE_HEIGHT_IN_UNITS_OF_ELEMETNS': GPU_TILE_HEIGHT_IN_UNITS_OF_ELEMETNS,
        'MAT_A_INPUT_SIZE_B': MAT_A_INPUT_SIZE_B,
        'MAT_B_INPUT_SIZE_B': MAT_B_INPUT_SIZE_B,
        'MAT_C_INPUT_D_OUTPUT_SIZE_B': MAT_C_INPUT_D_OUTPUT_SIZE_B,
        'MAT_D_INTERMEDIATE_SIZE_B': MAT_D_INTERMEDIATE_SIZE_B,
        'TOTAL_L2_READ_B': TOTAL_L2_READ_B,
        'TOTAL_L2_WRITE_B': TOTAL_L2_WRITE_B,
        'TOTAL_L1_READ_B': TOTAL_L1_READ_B,
        'TOTAL_L1_WRITE_B': TOTAL_L1_WRITE_B,
        'L2_READ_B_XECORE_CLK': L2_READ_B_XECORE_CLK,
        'L2_WRITE_B_XECORE_CLK': L2_WRITE_B_XECORE_CLK,
        'L2_READ_WRITE_B_XECORE_CLK': L2_READ_WRITE_B_XECORE_CLK,
        'L1_READ_B_EU_CLK': L1_READ_B_EU_CLK,
        'L1_READ_B_XECORE_CLK': L1_READ_B_XECORE_CLK,
        'L1_WRITE_B_EU_CLK': L1_WRITE_B_EU_CLK,
        'L1_WRITE_B_XECORECLK': L1_WRITE_B_XECORECLK,
        'L2_READ_MAX_B_XECORE_CLK': L2_READ_MAX_B_XECORE_CLK,
        'L2_WRITE_MAX_B_XECORE_CLK': L2_WRITE_MAX_B_XECORE_CLK,
        'L2_READ_WRITE_MAX_B_XECORE_CLK': L2_READ_WRITE_MAX_B_XECORE_CLK,
        'L2_READ_B_XECORE_CLK_PCT': L2_READ_B_XECORE_CLK_PCT,
        'L2_WRITE_B_XECORE_CLK_PCT': L2_WRITE_B_XECORE_CLK_PCT,
        'L2_READ_WRITE_B_XECORE_CLK_PCT': L2_READ_WRITE_B_XECORE_CLK_PCT,
        'L1_READ_B_EU_CLK_PCT': L1_READ_B_EU_CLK_PCT,
        'L1_WRITE_B_EU_CLK_PCT': L1_WRITE_B_EU_CLK_PCT,
        'TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE': TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE,
        'WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE': WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE,
        'TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE': TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE,
        'L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT': L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT,
        'L2_MISS_RATE_PCT': L2_MISS_RATE_PCT,
        'TOTAL_L2_READ_TRAFFIC_B': TOTAL_L2_READ_TRAFFIC_B,
        'PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT,
        'PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT,
        'PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT,
        'PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT,
        'TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE': TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE,
        'TOTAL_HBM_WRITE_B': TOTAL_HBM_WRITE_B,
        'TOTAL_HBM_B': TOTAL_HBM_B,
        'HBM_READ_B_CLK': HBM_READ_B_CLK,
        'HBM_WRITE_B_CLK': HBM_WRITE_B_CLK,
        'HBM_TOTAL_B_CLK': HBM_TOTAL_B_CLK,
        'MAX_POSSIBLE_HBM_BW_FREQ_B_CLK': MAX_POSSIBLE_HBM_BW_FREQ_B_CLK,
        'HBM_BW_PCT': HBM_BW_PCT,
        'GTI_READ_BW_PCT': GTI_READ_BW_PCT,
        'GTI_WRITE_BW_PCT': GTI_WRITE_BW_PCT,
    }

# ===========================
# Category metadata
# ===========================

FORMAT_KEY_NAMES = ['INPUT_A_DATA_FORMAT', 'INPUT_B_DATA_FORMAT', 'OUTPUT_D_DATA_FORMAT']
WORKLOAD_PRE_NAMES = ['M', 'K', 'N', 'OUTPUT_BYTES_PER_ELEMENT_FP32', 'MACHINE_OCCUPANCY_PCT', 'M_PER_THREAD', 'K_PER_THREAD', 'N_PER_THREAD', 'TG_WIDTH_IN_UNITS_OF_THREAD', 'TG_HEIGHT_IN_UNITS_OF_THREAD', 'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4', 'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4', 'XECU_TILE_WIDTH_IN_UNITS_OF_TG', 'XECU_TILE_HEIGHT_IN_UNITS_OF_TG', 'GPU_TILE_WIDTH_IN_XECU_UNIT']
MACHINE_PRE_NAMES = ['GT_FREQ_GHZ', 'XECU_COUNT', 'XECORE_PER_XECU', 'EU_PER_XECORE', 'L2_BANKS_PER_XECU', 'BANK_CAPACITY_MB', 'DPAS_DEPTH', 'COMPUTE_EFFICIENCY_PCT', 'L1_READ_MAX_B_EU_CLK', 'L1_WRITE_MAX_B_EU_CLK', 'GTI_READ_MAX_BW_B_CLK', 'GTI_WRITE_MAX_BW_B_CLK', 'MAX_POSSIBLE_HBM_BW_GB_S']
WORKLOAD_FMT_VAL_NAMES = ['INPUT_A_BYTES_PER_ELEMENT', 'INPUT_B_BYTES_PER_ELEMENT', 'OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION']
WORKLOAD_DERIVED_NAMES = ['WAVES', 'TG_TILES_IN_N', 'TG_TILES_IN_M', 'TG_CLUSTER_TILES_IN_N', 'TG_CLUSTER_TILES_IN_M', 'XECU_TILES_IN_N', 'XECU_TILES_IN_M', 'GPU_TILES_IN_N', 'GPU_TILES_IN_M', 'THREAD_WIDTH_IN_UNITS_OF_ELEMENTS', 'THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS', 'TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS', 'TG_HEIGHT_IN_UNITS_OF_ELEMENT', 'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT', 'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT', 'XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT', 'XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT', 'GPU_TILE_HEIGHT_IN_XECU_UINT', 'GPU_TILE_WIDTH_IN_UNITS_OF_ELEMETNS', 'GPU_TILE_HEIGHT_IN_UNITS_OF_ELEMETNS', 'MAT_A_INPUT_SIZE_B', 'MAT_B_INPUT_SIZE_B', 'MAT_C_INPUT_D_OUTPUT_SIZE_B', 'MAT_D_INTERMEDIATE_SIZE_B', 'WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE', 'TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE']
MACHINE_DERIVED_NAMES = ['EU_COUNT', 'TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE', 'MAX_POSSIBLE_HBM_BW_FREQ_B_CLK']
MACHINE_WL_DERIVED_NAMES = ['MMA_MAC_THROUGHPUT_PER_XECORE', 'CLKS_PER_DPAS']
MACHINE_STATS_NAMES = ['CLK_SPECIFIED_EFFICIENCY', 'TOTAL_L2_READ_B', 'TOTAL_L2_WRITE_B', 'TOTAL_L1_READ_B', 'TOTAL_L1_WRITE_B', 'L2_READ_B_XECORE_CLK', 'L2_WRITE_B_XECORE_CLK', 'L2_READ_WRITE_B_XECORE_CLK', 'L1_READ_B_XECORE_CLK', 'L1_WRITE_B_XECORECLK', 'L1_READ_B_EU_CLK', 'L1_WRITE_B_EU_CLK', 'L2_READ_MAX_B_XECORE_CLK', 'L2_WRITE_MAX_B_XECORE_CLK', 'L2_READ_WRITE_MAX_B_XECORE_CLK', 'L2_READ_B_XECORE_CLK_PCT', 'L2_WRITE_B_XECORE_CLK_PCT', 'L2_READ_WRITE_B_XECORE_CLK_PCT', 'L1_READ_B_EU_CLK_PCT', 'L1_WRITE_B_EU_CLK_PCT', 'L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT', 'L2_MISS_RATE_PCT', 'TOTAL_L2_READ_TRAFFIC_B', 'PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE', 'TOTAL_HBM_WRITE_B', 'TOTAL_HBM_B', 'HBM_READ_B_CLK', 'HBM_WRITE_B_CLK', 'HBM_TOTAL_B_CLK', 'HBM_BW_PCT', 'GTI_READ_BW_PCT', 'GTI_WRITE_BW_PCT']
ALL_WORKLOAD_PRE_NAMES = FORMAT_KEY_NAMES + WORKLOAD_PRE_NAMES
ALL_PRE_NAMES_SET = set(ALL_WORKLOAD_PRE_NAMES + MACHINE_PRE_NAMES)
PERCENT_NAMES = ['MACHINE_OCCUPANCY_PCT', 'COMPUTE_EFFICIENCY_PCT', 'L2_READ_B_XECORE_CLK_PCT', 'L2_WRITE_B_XECORE_CLK_PCT', 'L2_READ_WRITE_B_XECORE_CLK_PCT', 'L1_READ_B_EU_CLK_PCT', 'L1_WRITE_B_EU_CLK_PCT', 'L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT', 'L2_MISS_RATE_PCT', 'PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'HBM_BW_PCT', 'GTI_READ_BW_PCT', 'GTI_WRITE_BW_PCT']

# Order following 4-section compute function execution: Section 1 -> 2 -> 3 -> 4
COMPUTE_ORDER = (
    MACHINE_PRE_NAMES +
    FORMAT_KEY_NAMES + WORKLOAD_PRE_NAMES +
    WORKLOAD_FMT_VAL_NAMES + MACHINE_DERIVED_NAMES + MACHINE_WL_DERIVED_NAMES + WORKLOAD_DERIVED_NAMES +
    MACHINE_STATS_NAMES
)

ROW_INDEX = {'INPUT_A_DATA_FORMAT': 3, 'INPUT_B_DATA_FORMAT': 4, 'OUTPUT_D_DATA_FORMAT': 5, 'GT_FREQ_GHZ': 8, 'M': 9, 'K': 10, 'N': 11, 'WAVES': 13, 'TG_TILES_IN_N': 14, 'TG_TILES_IN_M': 15, 'TG_CLUSTER_TILES_IN_N': 16, 'TG_CLUSTER_TILES_IN_M': 17, 'XECU_TILES_IN_N': 18, 'XECU_TILES_IN_M': 19, 'GPU_TILES_IN_N': 20, 'GPU_TILES_IN_M': 21, 'INPUT_A_BYTES_PER_ELEMENT': 22, 'INPUT_B_BYTES_PER_ELEMENT': 23, 'OUTPUT_BYTES_PER_ELEMENT_FP32': 24, 'OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION': 25, 'XECU_COUNT': 26, 'XECORE_PER_XECU': 27, 'EU_PER_XECORE': 28, 'L2_BANKS_PER_XECU': 29, 'BANK_CAPACITY_MB': 30, 'DPAS_DEPTH': 32, 'EU_COUNT': 33, 'MACHINE_OCCUPANCY_PCT': 34, 'COMPUTE_EFFICIENCY_PCT': 35, 'MMA_MAC_THROUGHPUT_PER_XECORE': 36, 'CLK_SPECIFIED_EFFICIENCY': 37, 'M_PER_THREAD': 39, 'K_PER_THREAD': 40, 'N_PER_THREAD': 41, 'CLKS_PER_DPAS': 42, 'THREAD_WIDTH_IN_UNITS_OF_ELEMENTS': 43, 'THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS': 44, 'TG_WIDTH_IN_UNITS_OF_THREAD': 45, 'TG_HEIGHT_IN_UNITS_OF_THREAD': 46, 'TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS': 47, 'TG_HEIGHT_IN_UNITS_OF_ELEMENT': 48, 'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4': 50, 'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4': 51, 'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT': 52, 'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT': 53, 'XECU_TILE_WIDTH_IN_UNITS_OF_TG': 54, 'XECU_TILE_HEIGHT_IN_UNITS_OF_TG': 55, 'XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT': 56, 'XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT': 57, 'GPU_TILE_WIDTH_IN_XECU_UNIT': 58, 'GPU_TILE_HEIGHT_IN_XECU_UINT': 59, 'GPU_TILE_WIDTH_IN_UNITS_OF_ELEMETNS': 60, 'GPU_TILE_HEIGHT_IN_UNITS_OF_ELEMETNS': 61, 'MAT_A_INPUT_SIZE_B': 63, 'MAT_B_INPUT_SIZE_B': 64, 'MAT_C_INPUT_D_OUTPUT_SIZE_B': 65, 'MAT_D_INTERMEDIATE_SIZE_B': 66, 'TOTAL_L2_READ_B': 69, 'TOTAL_L2_WRITE_B': 70, 'TOTAL_L1_READ_B': 71, 'TOTAL_L1_WRITE_B': 72, 'L2_READ_B_XECORE_CLK': 74, 'L2_WRITE_B_XECORE_CLK': 75, 'L2_READ_WRITE_B_XECORE_CLK': 76, 'L1_READ_B_XECORE_CLK': 77, 'L1_WRITE_B_XECORECLK': 78, 'L1_READ_B_EU_CLK': 79, 'L1_WRITE_B_EU_CLK': 80, 'L2_READ_MAX_B_XECORE_CLK': 83, 'L2_WRITE_MAX_B_XECORE_CLK': 84, 'L2_READ_WRITE_MAX_B_XECORE_CLK': 85, 'L1_READ_MAX_B_EU_CLK': 86, 'L1_WRITE_MAX_B_EU_CLK': 87, 'L2_READ_B_XECORE_CLK_PCT': 90, 'L2_WRITE_B_XECORE_CLK_PCT': 91, 'L2_READ_WRITE_B_XECORE_CLK_PCT': 92, 'L1_READ_B_EU_CLK_PCT': 93, 'L1_WRITE_B_EU_CLK_PCT': 94, 'GTI_READ_MAX_BW_B_CLK': 97, 'GTI_WRITE_MAX_BW_B_CLK': 98, 'TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE': 102, 'WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE': 103, 'TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE': 104, 'L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT': 106, 'L2_MISS_RATE_PCT': 107, 'TOTAL_L2_READ_TRAFFIC_B': 108, 'PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': 110, 'PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': 111, 'PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': 112, 'PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': 113, 'TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE': 116, 'TOTAL_HBM_WRITE_B': 117, 'TOTAL_HBM_B': 118, 'HBM_READ_B_CLK': 121, 'HBM_WRITE_B_CLK': 122, 'HBM_TOTAL_B_CLK': 123, 'MAX_POSSIBLE_HBM_BW_GB_S': 124, 'MAX_POSSIBLE_HBM_BW_FREQ_B_CLK': 125, 'HBM_BW_PCT': 126, 'GTI_READ_BW_PCT': 127, 'GTI_WRITE_BW_PCT': 128}
ROW_ORDER = ['INPUT_A_DATA_FORMAT', 'INPUT_B_DATA_FORMAT', 'OUTPUT_D_DATA_FORMAT', 'GT_FREQ_GHZ', 'M', 'K', 'N', 'WAVES', 'TG_TILES_IN_N', 'TG_TILES_IN_M', 'TG_CLUSTER_TILES_IN_N', 'TG_CLUSTER_TILES_IN_M', 'XECU_TILES_IN_N', 'XECU_TILES_IN_M', 'GPU_TILES_IN_N', 'GPU_TILES_IN_M', 'INPUT_A_BYTES_PER_ELEMENT', 'INPUT_B_BYTES_PER_ELEMENT', 'OUTPUT_BYTES_PER_ELEMENT_FP32', 'OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION', 'XECU_COUNT', 'XECORE_PER_XECU', 'EU_PER_XECORE', 'L2_BANKS_PER_XECU', 'BANK_CAPACITY_MB', 'DPAS_DEPTH', 'EU_COUNT', 'MACHINE_OCCUPANCY_PCT', 'COMPUTE_EFFICIENCY_PCT', 'MMA_MAC_THROUGHPUT_PER_XECORE', 'CLK_SPECIFIED_EFFICIENCY', 'M_PER_THREAD', 'K_PER_THREAD', 'N_PER_THREAD', 'CLKS_PER_DPAS', 'THREAD_WIDTH_IN_UNITS_OF_ELEMENTS', 'THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS', 'TG_WIDTH_IN_UNITS_OF_THREAD', 'TG_HEIGHT_IN_UNITS_OF_THREAD', 'TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS', 'TG_HEIGHT_IN_UNITS_OF_ELEMENT', 'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4', 'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4', 'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT', 'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT', 'XECU_TILE_WIDTH_IN_UNITS_OF_TG', 'XECU_TILE_HEIGHT_IN_UNITS_OF_TG', 'XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT', 'XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT', 'GPU_TILE_WIDTH_IN_XECU_UNIT', 'GPU_TILE_HEIGHT_IN_XECU_UINT', 'GPU_TILE_WIDTH_IN_UNITS_OF_ELEMETNS', 'GPU_TILE_HEIGHT_IN_UNITS_OF_ELEMETNS', 'MAT_A_INPUT_SIZE_B', 'MAT_B_INPUT_SIZE_B', 'MAT_C_INPUT_D_OUTPUT_SIZE_B', 'MAT_D_INTERMEDIATE_SIZE_B', 'TOTAL_L2_READ_B', 'TOTAL_L2_WRITE_B', 'TOTAL_L1_READ_B', 'TOTAL_L1_WRITE_B', 'L2_READ_B_XECORE_CLK', 'L2_WRITE_B_XECORE_CLK', 'L2_READ_WRITE_B_XECORE_CLK', 'L1_READ_B_XECORE_CLK', 'L1_WRITE_B_XECORECLK', 'L1_READ_B_EU_CLK', 'L1_WRITE_B_EU_CLK', 'L2_READ_MAX_B_XECORE_CLK', 'L2_WRITE_MAX_B_XECORE_CLK', 'L2_READ_WRITE_MAX_B_XECORE_CLK', 'L1_READ_MAX_B_EU_CLK', 'L1_WRITE_MAX_B_EU_CLK', 'L2_READ_B_XECORE_CLK_PCT', 'L2_WRITE_B_XECORE_CLK_PCT', 'L2_READ_WRITE_B_XECORE_CLK_PCT', 'L1_READ_B_EU_CLK_PCT', 'L1_WRITE_B_EU_CLK_PCT', 'GTI_READ_MAX_BW_B_CLK', 'GTI_WRITE_MAX_BW_B_CLK', 'TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE', 'WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE', 'TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE', 'L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT', 'L2_MISS_RATE_PCT', 'TOTAL_L2_READ_TRAFFIC_B', 'PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE', 'TOTAL_HBM_WRITE_B', 'TOTAL_HBM_B', 'HBM_READ_B_CLK', 'HBM_WRITE_B_CLK', 'HBM_TOTAL_B_CLK', 'MAX_POSSIBLE_HBM_BW_GB_S', 'MAX_POSSIBLE_HBM_BW_FREQ_B_CLK', 'HBM_BW_PCT', 'GTI_READ_BW_PCT', 'GTI_WRITE_BW_PCT']

# ===========================
# LaTeX symbol scaffold (user editable)
# ===========================
# Purpose:
# - Provide a single place to map internal variable names to custom LaTeX symbols.
# - Leave a value as '' to use automatic fallback rendering.
# - Recommended format for custom values: r'\\mathrm{GT\\_FREQ\\_GHZ}'

LATEX_SYMBOL_OVERRIDES = {
    # ---- Machine pre-defined ----
    'GT_FREQ_GHZ': r'\mathrm{f_{GHz}^{(GT)}}',
    'XECU_COUNT': r'\mathrm{|XeCU|}',
    'XECORE_PER_XECU': r'\mathrm{|XeCore|_{pXeCU}}',
    'EU_PER_XECORE': r'\mathrm{|EU|_{pXeCore}}',
    'L2_BANKS_PER_XECU': r'\mathrm{|L2Banks|_{pXeCU}}',
    'BANK_CAPACITY_MB': r'\mathrm{L2BankSize_{MB}}',
    'DPAS_DEPTH': r'\mathrm{D_{DPAS}}',
    'COMPUTE_EFFICIENCY_PCT': r'\mathrm{\eta_{systolic}}',
    'L1_READ_MAX_B_EU_CLK': r'\mathrm{L1RdB_{BpClk{\cdot}EU}^{max}}',
    'L1_WRITE_MAX_B_EU_CLK': r'\mathrm{L1WrB_{BpClk{\cdot}EU}^{max}}',
    'GTI_READ_MAX_B_EU_CLK': r'\mathrm{GtiRdB_{BpClk}^{max}}',
    'GTI_WRITE_MAX_B_EU_CLK': r'\mathrm{GtiWrB_{BpClk}^{max}}',
    'MAX_POSSIBLE_HBM_BW_GB_S': r'\mathrm{MemBW_{GBps}^{max}}',

    # ---- Workload format keys + pre-defined ----
    'INPUT_A_DATA_FORMAT': r'\mathrm{Fmt^{(matA)}}',
    'INPUT_B_DATA_FORMAT': r'\mathrm{Fmt^{(matB)}}',
    'OUTPUT_D_DATA_FORMAT': r'\mathrm{Fmt^{(matD\downarrow)}}',
    'M': r'\mathrm{M_{dim}}',
    'K': r'\mathrm{K_{dim}}',
    'N': r'\mathrm{N_{dim}}',
    'OUTPUT_BYTES_PER_ELEMENT_FP32': r'\mathrm{Byte_{pElement}^{(matD)}}',
    'MACHINE_OCCUPANCY_PCT': r'\mathrm{\rho_{GT}}',
    'M_PER_THREAD': r'\mathrm{M_{pThread}}',
    'K_PER_THREAD': r'\mathrm{K_{pThread}}',
    'N_PER_THREAD': r'\mathrm{N_{pThread}}',
    'TG_WIDTH_IN_UNITS_OF_THREAD': r'\mathrm{W_{thread}^{(ThreadGroup)}}',
    'TG_HEIGHT_IN_UNITS_OF_THREAD': r'\mathrm{H_{thread}^{(ThreadGroup)}}',
    'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4': r'\mathrm{W_{TG,keep\ cluster\ size\ as\ 4}^{(XeCoreCluster)}}',
    'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4': r'\mathrm{H_{TG,keep\ cluster\ size\ as\ 4}^{(XeCoreCluster)}}',
    'XECU_TILE_WIDTH_IN_UNITS_OF_TG': r'\mathrm{W_{TG}^{(XECUTile)}}',
    'XECU_TILE_HEIGHT_IN_UNITS_OF_TG': r'\mathrm{H_{TG}^{(XECUTile)}}',
    'GPU_TILE_WIDTH_IN_XECU_UNIT': r'\mathrm{W_{XeCU}^{(GPUTile)}}',

    # ---- Workload derived ----
    'WAVES': r'\mathrm{N_{waves}}',
    'TG_TILES_IN_N': r'\mathrm{|Tiles|_{N}^{(TG)}}',
    'TG_TILES_IN_M': r'\mathrm{|Tiles|_{M}^{(TG)}}',
    'TG_CLUSTER_TILES_IN_N': r'\mathrm{|Tiles|_{N}^{(TG\ Cluster)}}',
    'TG_CLUSTER_TILES_IN_M': r'\mathrm{|Tiles|_{M}^{(TG\ Cluster)}}',
    'XECU_TILES_IN_N': r'\mathrm{|Tiles|_{N}^{(XeCU)}}',
    'XECU_TILES_IN_M': r'\mathrm{|Tiles|_{M}^{(XeCU)}}',
    'GPU_TILES_IN_N': r'\mathrm{|Tiles|_{N}^{(GPU)}}',
    'GPU_TILES_IN_M': r'\mathrm{|Tiles|_{M}^{(GPU)}}',
    'INPUT_A_BYTES_PER_ELEMENT': r'\mathrm{Bytes_{pElement}^{(matA)}}',
    'INPUT_B_BYTES_PER_ELEMENT': r'\mathrm{Bytes_{pElement}^{(matB)}}',
    'OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION': r'\mathrm{Bytes_{pElement}^{(D\downarrow)}}',
    'THREAD_WIDTH_IN_UNITS_OF_ELEMENTS': r'\mathrm{W_{element}^{(Thread)}}',
    'THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS': r'\mathrm{H_{element}^{(Thread)}}',
    'TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS': r'\mathrm{W_{element}^{(ThreadGroup, realized\ by\ multiple\ MMA\ iterations)}}',
    'TG_HEIGHT_IN_UNITS_OF_ELEMENT': r'\mathrm{H_{element}^{(ThreadGroup)}}',
    'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT': r'\mathrm{W_{element}^{(XeCoreCluster)}}',
    'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT': r'\mathrm{H_{element}^{(XeCoreCluster)}}',
    'XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT': r'\mathrm{W_{element}^{(XeCUTile)}}',
    'XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT': r'\mathrm{H_{element}^{(XeCUTile)}}',
    'GPU_TILE_HEIGHT_IN_XECU_UINT': r'\mathrm{H_{XeCU}^{(GPUTile)}}',
    'GPU_TILE_WIDTH_IN_UNITS_OF_ELEMETNS': r'\mathrm{W_{element}^{(GPUTile)}}',
    'GPU_TILE_HEIGHT_IN_UNITS_OF_ELEMETNS': r'\mathrm{H_{element}^{(GPUTile)}}',
    'MAT_A_INPUT_SIZE_B': r'\mathrm{Size_{B}^{(matA)}}',
    'MAT_B_INPUT_SIZE_B': r'\mathrm{Size_{B}^{(matB)}}',
    'MAT_C_INPUT_D_OUTPUT_SIZE_B': r'\mathrm{Size_{B}^{(matC,matD)}}',
    'MAT_D_INTERMEDIATE_SIZE_B': r'\mathrm{Size_{B}^{(matD\downarrow)}}',
    'WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE': r'\mathrm{|WorkingSet|_{20K\ clks\ of\ thread\ divergence}^{(K\ in\ L2)}}',
    'TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE': r'\mathrm{TotalRequiredL2Size_{matB\ always hit}^{1\ instance,\ 1\ wave}}',

    # ---- Machine / machine+workload derived ----
    'EU_COUNT': r'\mathrm{|EU|}',
    'TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE': r'\mathrm{|L2|_{B}}',
    'MAX_POSSIBLE_HBM_BW_FREQ_B_CLK': r'\mathrm{MemBW_{BpClk}^{max}}',
    'MMA_MAC_THROUGHPUT_PER_XECORE': r'\mathrm{\tau_{mMACpClk{\cdot}XeCore}^{(peak)}}',
    'CLKS_PER_DPAS': r'\mathrm{CLKS_{DPAS}}',

    # ---- Machine stats ----
    'CLK_SPECIFIED_EFFICIENCY': r'\mathrm{T_{clk}^{(total)}}',
    'TOTAL_L2_READ_B': r'\mathrm{L2Rd_{B}^{(total)}}',
    'TOTAL_L2_WRITE_B': r'\mathrm{L2Wr_{B}^{(total)}}',
    'TOTAL_L1_READ_B': r'\mathrm{L1Rd_{B}^{(total)}}',
    'TOTAL_L1_WRITE_B': r'\mathrm{L1Wr_{B}^{(total)}}',
    'L2_READ_B_XECORE_CLK': r'\mathrm{L2RdBW_{Bp(Clk{\cdot}XeCore)}}',
    'L2_WRITE_B_XECORE_CLK': r'\mathrm{L2WrBW_{Bp(Clk{\cdot}XeCore)}}',
    'L2_READ_WRITE_B_XECORE_CLK': r'\mathrm{L2RdWrBW_{Bp(Clk{\cdot}XeCore)}}',
    'L1_READ_B_XECORE_CLK': r'\mathrm{L1RdBW_{Bp(Clk{\cdot}XeCore)}}',
    'L1_WRITE_B_XECORECLK': r'\mathrm{L1WrBW_{Bp(Clk{\cdot}XeCore)}}',
    'L1_READ_B_EU_CLK': r'\mathrm{L1RdBW_{Bp(Clk{\cdot}EU)}}',
    'L1_WRITE_B_EU_CLK': r'\mathrm{L1WrBW_{Bp(Clk{\cdot}EU)}}',
    'L2_READ_MAX_B_XECORE_CLK': r'\mathrm{L2RdBW_{Bp(Clk{\cdot}XeCore)}^{(max)}}',
    'L2_WRITE_MAX_B_XECORE_CLK': r'\mathrm{L2WrBW_{Bp(Clk{\cdot}XeCore)}^{(max)}}',
    'L2_READ_WRITE_MAX_B_XECORE_CLK': r'\mathrm{L2RdWrBW_{Bp(Clk{\cdot}XeCore)}^{(max)}}',
    'L2_READ_B_XECORE_CLK_PCT': r'\mathrm{\eta_{L2RdBWpXeCore}}',
    'L2_WRITE_B_XECORE_CLK_PCT': r'\mathrm{\eta_{L2WrBWpXeCore}}',
    'L2_READ_WRITE_B_XECORE_CLK_PCT': r'\mathrm{\eta_{L2RdWrBWpXeCore}}',
    'L1_READ_B_EU_CLK_PCT': r'\mathrm{\eta_{L1RdBWpEU}}',
    'L1_WRITE_B_EU_CLK_PCT': r'\mathrm{\eta_{L1WrBWpEU}}',
    'L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT': r'\mathrm{L2HitRate_{random\ WS\ access}}',
    'L2_MISS_RATE_PCT': r'\mathrm{L2MissRate}',
    'TOTAL_L2_READ_TRAFFIC_B': r'\mathrm{L2RdB_{total}}',
    'PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': r'\mathrm{P_{L2Hit,\ after\ 1st\ wave}^{(matA)}}',
    'PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': r'\mathrm{P_{L2Hit,\ after\ 1st\ wave}^{(matB)}}',
    'PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': r'\mathrm{P_{L2Miss,\ after\ 1st\ wave}^{(matA)}}',
    'PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': r'\mathrm{P_{L2Miss,\ after\ 1st\ wave}^{(matB)}}',
    'TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE': r'\mathrm{MemRdB_{cold\ start}^{(wave)}}',
    'TOTAL_HBM_WRITE_B': r'\mathrm{MemWrB^{(total)}}',
    'TOTAL_HBM_B': r'\mathrm{MemRdWrB^{(total)}}',
    'HBM_READ_B_CLK': r'\mathrm{MemRdB_{pClk}}',
    'HBM_WRITE_B_CLK': r'\mathrm{MemWrB_{pClk}}',
    'HBM_TOTAL_B_CLK': r'\mathrm{MemRdWrB_{pClk}}',
    'HBM_BW_PCT': r'\mathrm{\eta_{MemBW}}',
    'GTI_READ_BW_PCT': r'\mathrm{\eta_{GTIRdBW}}',
    'GTI_WRITE_BW_PCT': r'\mathrm{\eta_{GTIWrBW}}',
}


def default_latex_symbol(name: str) -> str:
    """Return safe default LaTeX for a variable name (uses hyphens to avoid KaTeX subscript issues)."""
    return r'\mathrm{' + name.replace('_', '-') + r'}'


SPECIAL_LATEX_SYMBOL_OVERRIDES = {
    # Keep helper constants readable in equations without underscore subscript parsing.
    'DATA_FORMAT_TO_BYTES': r'\mathrm{DataFormatToBytes}',
}


def latex_symbol_for(name: str) -> str:
    """Return custom LaTeX symbol if provided, else safe default."""
    special = SPECIAL_LATEX_SYMBOL_OVERRIDES.get(name, '')
    if special:
        return special
    custom = LATEX_SYMBOL_OVERRIDES.get(name, '')
    return custom if custom else default_latex_symbol(name)


def _formula_to_latex_expr(expr: str) -> str:
    """Convert a Python-style formula string into a LaTeX expression with vertical fractions."""

    cmp_ops = {
        ast.Lt: '<',
        ast.LtE: r'\le',
        ast.Gt: '>',
        ast.GtE: r'\ge',
        ast.Eq: '=',
        ast.NotEq: r'\ne',
    }

    bool_ops = {
        ast.And: r'\land',
        ast.Or: r'\lor',
    }

    func_names = {
        'MIN': r'\min',
        'MAX': r'\max',
        'CEILING': r'\mathrm{CEILING}',
        'FLOOR': r'\mathrm{FLOOR}',
        'IF': r'\mathrm{IF}',
    }

    def _wrap(text: str) -> str:
        return r'\left(' + text + r'\right)'

    def _render(node: ast.AST, parent_prec: int = 0) -> str:
        # Precedence: compare/bool=1, add/sub=2, mul/div=3, pow=4, atom/call=5
        if isinstance(node, ast.Name):
            return latex_symbol_for(node.id)

        if isinstance(node, ast.Constant):
            return str(node.value)

        if isinstance(node, ast.Subscript):
            base = _render(node.value, 5)
            index = _render(node.slice, 0)
            return f'{base}[{index}]'

        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
            fn = func_names.get(node.func.id, node.func.id)
            args = ', '.join(_render(a, 0) for a in node.args)
            return f'{fn}({args})'

        if isinstance(node, ast.UnaryOp):
            if isinstance(node.op, ast.USub):
                return '-' + _render(node.operand, 5)
            if isinstance(node.op, ast.UAdd):
                return _render(node.operand, 5)

        if isinstance(node, ast.BinOp):
            if isinstance(node.op, ast.Add):
                prec = 2
                left = _render(node.left, prec)
                right = _render(node.right, prec)
                out = f'{left} + {right}'
                return _wrap(out) if prec < parent_prec else out

            if isinstance(node.op, ast.Sub):
                prec = 2
                left = _render(node.left, prec)
                right = _render(node.right, prec + 1)
                out = f'{left} - {right}'
                return _wrap(out) if prec < parent_prec else out

            if isinstance(node.op, ast.Mult):
                prec = 3
                left = _render(node.left, prec)
                right = _render(node.right, prec)
                out = f'{left} \\times {right}'
                return _wrap(out) if prec < parent_prec else out

            if isinstance(node.op, ast.Div):
                prec = 3
                num = _render(node.left, 0)
                den = _render(node.right, 0)
                out = rf'\frac{{{num}}}{{{den}}}'
                return _wrap(out) if prec < parent_prec else out

            if isinstance(node.op, ast.Pow):
                prec = 4
                base = _render(node.left, prec)
                exp = _render(node.right, 0)
                out = rf'{base}^{{{exp}}}'
                return _wrap(out) if prec < parent_prec else out

        if isinstance(node, ast.Compare) and len(node.ops) == 1 and len(node.comparators) == 1:
            op = cmp_ops.get(type(node.ops[0]), '?')
            left = _render(node.left, 1)
            right = _render(node.comparators[0], 1)
            return f'{left} {op} {right}'

        if isinstance(node, ast.BoolOp):
            op = bool_ops.get(type(node.op), '?')
            return f' {op} '.join(_render(v, 1) for v in node.values)

        return _wrap(ast.unparse(node))

    tree = ast.parse(expr, mode='eval')
    return _render(tree.body, 0)


def _split_top_level_additive(expr: str) -> list[str]:
    """Split a LaTeX expression at top-level + and - operators (brace/paren-depth-aware)."""
    parts: list[str] = []
    depth = 0        # { } depth
    pdepth = 0       # \left( ... \right) depth
    i = 0
    start = 0
    while i < len(expr):
        if expr[i] == '{':
            depth += 1
        elif expr[i] == '}':
            depth -= 1
        elif expr[i:i+6] == r'\left(':
            pdepth += 1
            i += 5
        elif expr[i:i+7] == r'\right)':
            pdepth -= 1
            i += 6
        elif expr[i] in '+-' and depth == 0 and pdepth == 0:
            # binary operator: surrounded by spaces
            if i > 0 and expr[i - 1] == ' ' and i + 1 < len(expr) and expr[i + 1] == ' ':
                parts.append(expr[start:i].strip())
                start = i  # keep operator with following term
        i += 1
    tail = expr[start:].strip()
    if tail:
        parts.append(tail)
    return parts


def _brace_extract(s: str, start: int) -> tuple[str, int]:
    """Extract the content of balanced braces starting at index 'start' (must be '{').
    Returns (content, index_after_closing_brace)."""
    assert s[start] == '{'
    depth = 0
    i = start
    while i < len(s):
        if s[i] == '{':
            depth += 1
        elif s[i] == '}':
            depth -= 1
            if depth == 0:
                return s[start + 1:i], i + 1
        i += 1
    raise ValueError('Unmatched brace in LaTeX expression')


def _extract_top_frac(s: str) -> tuple[str, str] | None:
    """If s is exactly \\frac{num}{den} with nothing trailing, return (num, den), else None."""
    prefix = r'\frac{'
    if not s.startswith(prefix):
        return None
    try:
        num, after_num = _brace_extract(s, len(prefix) - 1)
        if after_num >= len(s) or s[after_num] != '{':
            return None
        den, after_den = _brace_extract(s, after_num)
        if after_den != len(s):
            return None
        return num, den
    except (ValueError, AssertionError):
        return None


def _make_aux_symbol(lhs: str, suffix: str) -> str:
    """Return a parenthesized symbol with subscript for recursive decomposition."""
    return f'\\left({lhs}\\right)_{{{suffix}}}'


def _extract_leading_left_right_group(s: str) -> tuple[str, str] | None:
    r"""If s starts with \left( ... \right), return (inside, trailing_suffix)."""
    if not s.startswith(r'\left('):
        return None
    depth = 0
    i = 0
    while i < len(s):
        if s[i:i + 6] == r'\left(':
            depth += 1
            i += 6
            continue
        if s[i:i + 7] == r'\right)':
            depth -= 1
            i += 7
            if depth == 0:
                inner = s[6:i - 7]
                suffix = s[i:]
                return inner, suffix
            continue
        i += 1
    return None


def _equation_block(lhs: str, rhs: str, threshold: int = 100) -> str:
    """Return one or more markdown display-math blocks.

    Short equations:  single $$ ... $$ line.
    Long additive RHS: one aligned block split at top-level +/-.
    Long fraction RHS: three equations —
        (1) lhs = lhs_{num} / lhs_{den}  (or  lhs = lhs_{num} / simple_den)
        (2) lhs_{num} = <numerator>       (recursively wrapped if still long)
        (3) lhs_{den} = <denominator>     (only when denominator is complex)
    """
    if len(lhs) + len(rhs) + 5 <= threshold:
        return f'$$ {lhs} = {rhs} $$'

    # Case 1: top-level additive — split on + / -
    parts = _split_top_level_additive(rhs)
    if len(parts) > 1:
        extra_blocks: list[str] = []
        display_parts: list[str] = [parts[0]]

        for i, p in enumerate(parts[1:], start=1):
            sign = ''
            body = p
            if p.startswith('+ ') or p.startswith('- '):
                sign = p[:2]
                body = p[2:]

            # If a single additive term is still very long, extract a leading
            # parenthesized chunk into an auxiliary symbol and render it below.
            # This avoids overly wide lines like: +(A - (B + C + ...)) * R.
            group = _extract_leading_left_right_group(body) if len(p) > threshold else None
            if group:
                group_inner, group_suffix = group
                group_parts = _split_top_level_additive(group_inner)
                if len(group_parts) > 1:
                    aux = _make_aux_symbol(lhs, rf'\mathrm{{aux{i}}}')
                    display_parts.append(f'{sign}{aux}{group_suffix}')
                    extra_blocks.append(_equation_block(aux, group_inner, threshold))
                    continue

            display_parts.append(p)

        inner = f'{lhs} &= {display_parts[0]}'
        for p in display_parts[1:]:
            inner += f' \\\\\n&\\quad {p}'

        main_block = f'$$\n\\begin{{aligned}}\n{inner}\n\\end{{aligned}}\n$$'
        if not extra_blocks:
            return main_block
        return main_block + '\n\n' + '\n\n'.join(extra_blocks)

    # Case 2: single top-level \frac — decompose into 2 or 3 sub-equations
    frac = _extract_top_frac(rhs)
    if frac:
        num, den = frac
        component_long_threshold = max(120, threshold)
        num_is_very_long = len(num) > component_long_threshold
        den_is_very_long = len(den) > component_long_threshold

        # Keep compact fractions as a single equation even when lhs is long.
        if not num_is_very_long and not den_is_very_long:
            return f'$$ {lhs} = {rhs} $$'

        lhs_num = _make_aux_symbol(lhs, r'\mathrm{num}')
        den_is_simple = len(den) < 50 and r'\frac' not in den
        if den_is_simple:
            summary = f'$$ {lhs} = \\frac{{{lhs_num}}}{{{den}}} $$'
            num_block = _equation_block(lhs_num, num, threshold)
            return summary + '\n\n' + num_block
        else:
            lhs_den = _make_aux_symbol(lhs, r'\mathrm{den}')
            summary = f'$$ {lhs} = \\frac{{{lhs_num}}}{{{lhs_den}}} $$'
            num_block = _equation_block(lhs_num, num, threshold)
            den_block = _equation_block(lhs_den, den, threshold)
            return summary + '\n\n' + num_block + '\n\n' + den_block

    return f'$$ {lhs} = {rhs} $$'


def _format_equation_header(row: int | str, name: str, max_chars: int = 56) -> list[str]:
    """Format equation section headers and wrap long names at underscore boundaries."""
    words = name.split('_')
    wrapped: list[str] = []
    current: list[str] = []
    current_len = 0

    for w in words:
        add_len = len(w) + (1 if current else 0)
        if current and current_len + add_len > max_chars:
            wrapped.append(' '.join(current))
            current = [w]
            current_len = len(w)
        else:
            current.append(w)
            current_len += add_len

    if current:
        wrapped.append(' '.join(current))

    if not wrapped:
        return [f'### row {row}']

    lines = [f'### row {row} - {wrapped[0]}']
    for tail in wrapped[1:]:
        lines.append(f'### {tail}')
    return lines


def build_equations_markdown(output_order: str = 'execution') -> str:
    """Build equations markdown using LATEX_SYMBOL_OVERRIDES + PYTHON_FORMULAS."""
    internal_order = _resolve_output_order(output_order)
    item_order = COMPUTE_ORDER if internal_order == 'compute' else ROW_ORDER

    lines: list[str] = []
    lines.append('# GEMM Analytical Model - Equations')
    lines.append('')
    lines.append('Auto-generated from PYTHON_FORMULAS and LATEX_SYMBOL_OVERRIDES in gemmanalytics.py.')
    lines.append('')
    lines.append(f'Output order: {output_order}')
    lines.append('')

    for name in item_order:
        formula = PYTHON_FORMULAS.get(name, '')
        if not formula:
            continue
        row = ROW_INDEX.get(name, '?')
        lines.extend(_format_equation_header(row, name))
        lines.append('')
        lhs = latex_symbol_for(name)
        rhs = _formula_to_latex_expr(formula)
        lines.append(_equation_block(lhs, rhs))
        lines.append('')

    return '\n'.join(lines).rstrip() + '\n'


def export_equations_markdown(md_path: str, output_order: str = 'execution') -> None:
    """Write generated equation markdown file."""
    content = build_equations_markdown(output_order=output_order)
    with open(md_path, 'w', encoding='utf-8') as f:
        f.write(content)
EXCEL_FORMULAS = {'INPUT_A_BYTES_PER_ELEMENT': '', 'INPUT_B_BYTES_PER_ELEMENT': '', 'OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION': '', 'EU_COUNT': '=C27*C28*C26', 'MMA_MAC_THROUGHPUT_PER_XECORE': '=MIN(4/(FLOOR(C22*2,1)/2),4/(FLOOR(C23*2,1)/2))*C32*16*C28', 'CLK_SPECIFIED_EFFICIENCY': '=C9*C10*C11/C27/C26/C36/C35', 'CLKS_PER_DPAS': '=C39*C40*C41/(C36/C28)', 'THREAD_WIDTH_IN_UNITS_OF_ELEMENTS': '=C41', 'THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS': '=C39', 'TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS': '=C45*C43', 'TG_TILES_IN_N': '=C11/C47', 'TG_HEIGHT_IN_UNITS_OF_ELEMENT': '=C46*C44', 'TG_TILES_IN_M': '=C9/C48', 'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT': '=C50*C47', 'TG_CLUSTER_TILES_IN_N': '=C11/C52', 'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT': '=C51*C48', 'TG_CLUSTER_TILES_IN_M': '=C9/C53', 'XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT': '=C54*C47', 'XECU_TILES_IN_N': '=C11/C56', 'GPU_TILES_IN_N': '=C11/C56/C58', 'XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT': '=C55*C48', 'XECU_TILES_IN_M': '=C9/C57', 'GPU_TILE_HEIGHT_IN_XECU_UINT': '=C26/C58', 'GPU_TILES_IN_M': '=C9/C57/C59', 'WAVES': '=CEILING(C20,1)*CEILING(C21,1)', 'GPU_TILE_WIDTH_IN_UNITS_OF_ELEMETNS': '=C58*C56', 'GPU_TILE_HEIGHT_IN_UNITS_OF_ELEMETNS': '=C59*C57', 'MAT_A_INPUT_SIZE_B': '=C9*C10*C22', 'MAT_B_INPUT_SIZE_B': '=C10*C11*C23', 'MAT_C_INPUT_D_OUTPUT_SIZE_B': '=C9*C11*C25', 'MAT_D_INTERMEDIATE_SIZE_B': '=C9*C11*C24', 'TOTAL_L2_READ_B': '=(C63*CEILING(C11/C47,1)+C64*CEILING(C9/C48,1))', 'TOTAL_L2_WRITE_B': '=C65', 'TOTAL_L1_READ_B': '=(C63*CEILING(C11/C43,1)+C64*CEILING(C9/C44,1))', 'TOTAL_L1_WRITE_B': '=C65', 'L2_READ_B_XECORE_CLK': '=C69/(C26*C27)/C37', 'L2_WRITE_B_XECORE_CLK': '=C70/(C26*C27)/C37', 'L2_READ_WRITE_B_XECORE_CLK': '=C74+C75', 'L1_READ_B_EU_CLK': '=C71/(C33)/C37', 'L1_READ_B_XECORE_CLK': '=C79*C28', 'L1_WRITE_B_EU_CLK': '=C72/(C33)/C37', 'L1_WRITE_B_XECORECLK': '=C80*C28', 'L2_READ_MAX_B_XECORE_CLK': '=C27*64/C27', 'L2_WRITE_MAX_B_XECORE_CLK': '=C83', 'L2_READ_WRITE_MAX_B_XECORE_CLK': '=C84', 'L2_READ_B_XECORE_CLK_PCT': '=C74/C83', 'L2_WRITE_B_XECORE_CLK_PCT': '=C75/C84', 'L2_READ_WRITE_B_XECORE_CLK_PCT': '=C76/C85', 'L1_READ_B_EU_CLK_PCT': '=C79/C86', 'L1_WRITE_B_EU_CLK_PCT': '=C80/C87', 'TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE': '=C30*C29*1024*1024', 'WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE': '=MIN(20000*(C40/C42),C10)', 'TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE': '=(C57*C22*C103)+(C56*C23*C103)+(C56*C57*C25)', 'L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT': '=MIN(C102/C104,1)', 'L2_MISS_RATE_PCT': '=1-C106', 'TOTAL_L2_READ_TRAFFIC_B': '=C69', 'PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': '=IF(C63+C64+C65 <= C102,100%, IF(C10>2*C103,0%,1-(C10-C103)/C103))', 'PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': '=IF(C63+C64+C65 <= C102,100%, 0%)', 'PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': '=1-C110', 'PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': '=1-C111', 'TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE': '=(C63+C63*(CEILING(C11/C56,1)-1)*C112+C64+C64*(CEILING(C9/C57,1)-1)*C113+(C108-(C63+C63*(CEILING(C11/C56,1)-1)*C112+C64+C64*(CEILING(C9/C57,1)-1)*C113))*C107)/2', 'TOTAL_HBM_WRITE_B': '=C65', 'TOTAL_HBM_B': '=C117+C116', 'HBM_READ_B_CLK': '=C116/C$37', 'HBM_WRITE_B_CLK': '=C117/C$37', 'HBM_TOTAL_B_CLK': '=C118/C$37', 'MAX_POSSIBLE_HBM_BW_FREQ_B_CLK': '=C124/C8', 'HBM_BW_PCT': '=C123/C125', 'GTI_READ_BW_PCT': '=C121/C97', 'GTI_WRITE_BW_PCT': '=C122/C98'}
PYTHON_FORMULAS = {'INPUT_A_BYTES_PER_ELEMENT': 'DATA_FORMAT_TO_BYTES[INPUT_A_DATA_FORMAT]', 'INPUT_B_BYTES_PER_ELEMENT': 'DATA_FORMAT_TO_BYTES[INPUT_B_DATA_FORMAT]', 'OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION': 'DATA_FORMAT_TO_BYTES[OUTPUT_D_DATA_FORMAT]', 'EU_COUNT': 'XECORE_PER_XECU*EU_PER_XECORE*XECU_COUNT', 'MMA_MAC_THROUGHPUT_PER_XECORE': 'MIN(4/(FLOOR(INPUT_A_BYTES_PER_ELEMENT*2,1)/2),4/(FLOOR(INPUT_B_BYTES_PER_ELEMENT*2,1)/2))*DPAS_DEPTH*16*EU_PER_XECORE', 'CLK_SPECIFIED_EFFICIENCY': 'M*K*N/XECORE_PER_XECU/XECU_COUNT/MMA_MAC_THROUGHPUT_PER_XECORE/COMPUTE_EFFICIENCY_PCT', 'CLKS_PER_DPAS': 'M_PER_THREAD*K_PER_THREAD*N_PER_THREAD/(MMA_MAC_THROUGHPUT_PER_XECORE/EU_PER_XECORE)', 'THREAD_WIDTH_IN_UNITS_OF_ELEMENTS': 'N_PER_THREAD', 'THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS': 'M_PER_THREAD', 'TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS': 'TG_WIDTH_IN_UNITS_OF_THREAD*THREAD_WIDTH_IN_UNITS_OF_ELEMENTS', 'TG_TILES_IN_N': 'N/TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS', 'TG_HEIGHT_IN_UNITS_OF_ELEMENT': 'TG_HEIGHT_IN_UNITS_OF_THREAD*THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS', 'TG_TILES_IN_M': 'M/TG_HEIGHT_IN_UNITS_OF_ELEMENT', 'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT': 'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4*TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS', 'TG_CLUSTER_TILES_IN_N': 'N/XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT', 'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT': 'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4*TG_HEIGHT_IN_UNITS_OF_ELEMENT', 'TG_CLUSTER_TILES_IN_M': 'M/XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT', 'XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT': 'XECU_TILE_WIDTH_IN_UNITS_OF_TG*TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS', 'XECU_TILES_IN_N': 'N/XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT', 'GPU_TILES_IN_N': 'N/XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT/GPU_TILE_WIDTH_IN_XECU_UNIT', 'XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT': 'XECU_TILE_HEIGHT_IN_UNITS_OF_TG*TG_HEIGHT_IN_UNITS_OF_ELEMENT', 'XECU_TILES_IN_M': 'M/XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT', 'GPU_TILE_HEIGHT_IN_XECU_UINT': 'XECU_COUNT/GPU_TILE_WIDTH_IN_XECU_UNIT', 'GPU_TILES_IN_M': 'M/XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT/GPU_TILE_HEIGHT_IN_XECU_UINT', 'WAVES': 'CEILING(GPU_TILES_IN_N,1)*CEILING(GPU_TILES_IN_M,1)', 'GPU_TILE_WIDTH_IN_UNITS_OF_ELEMETNS': 'GPU_TILE_WIDTH_IN_XECU_UNIT*XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT', 'GPU_TILE_HEIGHT_IN_UNITS_OF_ELEMETNS': 'GPU_TILE_HEIGHT_IN_XECU_UINT*XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT', 'MAT_A_INPUT_SIZE_B': 'M*K*INPUT_A_BYTES_PER_ELEMENT', 'MAT_B_INPUT_SIZE_B': 'K*N*INPUT_B_BYTES_PER_ELEMENT', 'MAT_C_INPUT_D_OUTPUT_SIZE_B': 'M*N*OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION', 'MAT_D_INTERMEDIATE_SIZE_B': 'M*N*OUTPUT_BYTES_PER_ELEMENT_FP32', 'TOTAL_L2_READ_B': '(MAT_A_INPUT_SIZE_B*CEILING(N/TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS,1)+MAT_B_INPUT_SIZE_B*CEILING(M/TG_HEIGHT_IN_UNITS_OF_ELEMENT,1))', 'TOTAL_L2_WRITE_B': 'MAT_C_INPUT_D_OUTPUT_SIZE_B', 'TOTAL_L1_READ_B': '(MAT_A_INPUT_SIZE_B*CEILING(N/THREAD_WIDTH_IN_UNITS_OF_ELEMENTS,1)+MAT_B_INPUT_SIZE_B*CEILING(M/THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS,1))', 'TOTAL_L1_WRITE_B': 'MAT_C_INPUT_D_OUTPUT_SIZE_B', 'L2_READ_B_XECORE_CLK': 'TOTAL_L2_READ_B/(XECU_COUNT*XECORE_PER_XECU)/CLK_SPECIFIED_EFFICIENCY', 'L2_WRITE_B_XECORE_CLK': 'TOTAL_L2_WRITE_B/(XECU_COUNT*XECORE_PER_XECU)/CLK_SPECIFIED_EFFICIENCY', 'L2_READ_WRITE_B_XECORE_CLK': 'L2_READ_B_XECORE_CLK+L2_WRITE_B_XECORE_CLK', 'L1_READ_B_EU_CLK': 'TOTAL_L1_READ_B/(EU_COUNT)/CLK_SPECIFIED_EFFICIENCY', 'L1_READ_B_XECORE_CLK': 'L1_READ_B_EU_CLK*EU_PER_XECORE', 'L1_WRITE_B_EU_CLK': 'TOTAL_L1_WRITE_B/(EU_COUNT)/CLK_SPECIFIED_EFFICIENCY', 'L1_WRITE_B_XECORECLK': 'L1_WRITE_B_EU_CLK*EU_PER_XECORE', 'L2_READ_MAX_B_XECORE_CLK': 'XECORE_PER_XECU*64/XECORE_PER_XECU', 'L2_WRITE_MAX_B_XECORE_CLK': 'L2_READ_MAX_B_XECORE_CLK', 'L2_READ_WRITE_MAX_B_XECORE_CLK': 'L2_WRITE_MAX_B_XECORE_CLK', 'L2_READ_B_XECORE_CLK_PCT': 'L2_READ_B_XECORE_CLK/L2_READ_MAX_B_XECORE_CLK', 'L2_WRITE_B_XECORE_CLK_PCT': 'L2_WRITE_B_XECORE_CLK/L2_WRITE_MAX_B_XECORE_CLK', 'L2_READ_WRITE_B_XECORE_CLK_PCT': 'L2_READ_WRITE_B_XECORE_CLK/L2_READ_WRITE_MAX_B_XECORE_CLK', 'L1_READ_B_EU_CLK_PCT': 'L1_READ_B_EU_CLK/L1_READ_MAX_B_EU_CLK', 'L1_WRITE_B_EU_CLK_PCT': 'L1_WRITE_B_EU_CLK/L1_WRITE_MAX_B_EU_CLK', 'TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE': 'BANK_CAPACITY_MB*L2_BANKS_PER_XECU*1024*1024', 'WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE': 'MIN(20000*(K_PER_THREAD/CLKS_PER_DPAS),K)', 'TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE': '(XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT*INPUT_A_BYTES_PER_ELEMENT*WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE)+(XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT*INPUT_B_BYTES_PER_ELEMENT*WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE)+(XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT*XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT*OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION)', 'L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT': 'MIN(TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE/TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE,1)', 'L2_MISS_RATE_PCT': '1-L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT', 'TOTAL_L2_READ_TRAFFIC_B': 'TOTAL_L2_READ_B', 'PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': 'IF(MAT_A_INPUT_SIZE_B+MAT_B_INPUT_SIZE_B+MAT_C_INPUT_D_OUTPUT_SIZE_B <= TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE,1.0, IF(K>2*WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE,0.0,1-(K-WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE)/WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE))', 'PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': 'IF(MAT_A_INPUT_SIZE_B+MAT_B_INPUT_SIZE_B+MAT_C_INPUT_D_OUTPUT_SIZE_B <= TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE,1.0, 0.0)', 'PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': '1-PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': '1-PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT', 'TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE': '(MAT_A_INPUT_SIZE_B+MAT_A_INPUT_SIZE_B*(CEILING(N/XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT,1)-1)*PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT+MAT_B_INPUT_SIZE_B+MAT_B_INPUT_SIZE_B*(CEILING(M/XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT,1)-1)*PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT+(TOTAL_L2_READ_TRAFFIC_B-(MAT_A_INPUT_SIZE_B+MAT_A_INPUT_SIZE_B*(CEILING(N/XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT,1)-1)*PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT+MAT_B_INPUT_SIZE_B+MAT_B_INPUT_SIZE_B*(CEILING(M/XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT,1)-1)*PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT))*L2_MISS_RATE_PCT)/2', 'TOTAL_HBM_WRITE_B': 'MAT_C_INPUT_D_OUTPUT_SIZE_B', 'TOTAL_HBM_B': 'TOTAL_HBM_WRITE_B+TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE', 'HBM_READ_B_CLK': 'TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE/CLK_SPECIFIED_EFFICIENCY', 'HBM_WRITE_B_CLK': 'TOTAL_HBM_WRITE_B/CLK_SPECIFIED_EFFICIENCY', 'HBM_TOTAL_B_CLK': 'TOTAL_HBM_B/CLK_SPECIFIED_EFFICIENCY', 'MAX_POSSIBLE_HBM_BW_FREQ_B_CLK': 'MAX_POSSIBLE_HBM_BW_GB_S/GT_FREQ_GHZ', 'HBM_BW_PCT': 'HBM_TOTAL_B_CLK/MAX_POSSIBLE_HBM_BW_FREQ_B_CLK', 'GTI_READ_BW_PCT': 'HBM_READ_B_CLK/GTI_READ_MAX_BW_B_CLK', 'GTI_WRITE_BW_PCT': 'HBM_WRITE_B_CLK/GTI_WRITE_MAX_BW_B_CLK'}
CATEGORY_MAP = {'INPUT_A_DATA_FORMAT': 'workload format key pre', 'INPUT_B_DATA_FORMAT': 'workload format key pre', 'OUTPUT_D_DATA_FORMAT': 'workload format key pre', 'GT_FREQ_GHZ': 'machine pre', 'M': 'workload pre', 'K': 'workload pre', 'N': 'workload pre', 'WAVES': 'workload derived', 'TG_TILES_IN_N': 'workload derived', 'TG_TILES_IN_M': 'workload derived', 'TG_CLUSTER_TILES_IN_N': 'workload derived', 'TG_CLUSTER_TILES_IN_M': 'workload derived', 'XECU_TILES_IN_N': 'workload derived', 'XECU_TILES_IN_M': 'workload derived', 'GPU_TILES_IN_N': 'workload derived', 'GPU_TILES_IN_M': 'workload derived', 'INPUT_A_BYTES_PER_ELEMENT': 'workload format value derived by data_format_to_bytes[c3]', 'INPUT_B_BYTES_PER_ELEMENT': 'workload format value derived by data_format_to_bytes[c4]', 'OUTPUT_BYTES_PER_ELEMENT_FP32': 'workload pre', 'OUTPUT_BYTES_PER_ELEMENT_AFTER_DOWN_CONVERSION': 'workload format value derived by data_format_to_bytes[c5]', 'XECU_COUNT': 'machine pre', 'XECORE_PER_XECU': 'machine pre', 'EU_PER_XECORE': 'machine pre', 'L2_BANKS_PER_XECU': 'machine pre', 'BANK_CAPACITY_MB': 'machine pre', 'DPAS_DEPTH': 'machine pre', 'EU_COUNT': 'machine derived', 'MACHINE_OCCUPANCY_PCT': 'workload pre', 'COMPUTE_EFFICIENCY_PCT': 'machine pre', 'MMA_MAC_THROUGHPUT_PER_XECORE': 'machine workload derived', 'CLK_SPECIFIED_EFFICIENCY': 'machine stats', 'M_PER_THREAD': 'workload pre', 'K_PER_THREAD': 'workload pre', 'N_PER_THREAD': 'workload pre', 'CLKS_PER_DPAS': 'machine workload derived', 'THREAD_WIDTH_IN_UNITS_OF_ELEMENTS': 'workload derived', 'THREAD_HEIGHT_IN_UNITS_OF_ELEMENTS': 'workload derived', 'TG_WIDTH_IN_UNITS_OF_THREAD': 'workload pre', 'TG_HEIGHT_IN_UNITS_OF_THREAD': 'workload pre', 'TG_WIDTH_IN_UNITS_OF_ELEMENT_REALIZED_BY_MULTIPLE_MMA_ITERATIONS': 'workload derived', 'TG_HEIGHT_IN_UNITS_OF_ELEMENT': 'workload derived', 'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4': 'workload pre', 'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_TG_KEEP_THE_CLUSTER_SIZE_AS_4': 'workload pre', 'XECORE_CLUSTER_WIDTH_IN_UNITS_OF_ELEMENT': 'workload derived', 'XECORE_CLUSTER_HEIGHT_IN_UNITS_OF_ELEMENT': 'workload derived', 'XECU_TILE_WIDTH_IN_UNITS_OF_TG': 'workload pre', 'XECU_TILE_HEIGHT_IN_UNITS_OF_TG': 'workload pre', 'XECU_TILE_WIDTH_IN_UNITS_OF_ELEMENT': 'workload derived', 'XECU_TILE_HEIGHT_IN_UNITS_OF_ELEMENT': 'workload derived', 'GPU_TILE_WIDTH_IN_XECU_UNIT': 'workload pre', 'GPU_TILE_HEIGHT_IN_XECU_UINT': 'workload derived', 'GPU_TILE_WIDTH_IN_UNITS_OF_ELEMETNS': 'workload derived', 'GPU_TILE_HEIGHT_IN_UNITS_OF_ELEMETNS': 'workload derived', 'MAT_A_INPUT_SIZE_B': 'workload derived', 'MAT_B_INPUT_SIZE_B': 'workload derived', 'MAT_C_INPUT_D_OUTPUT_SIZE_B': 'workload derived', 'MAT_D_INTERMEDIATE_SIZE_B': 'workload derived', 'TOTAL_L2_READ_B': 'machine stats', 'TOTAL_L2_WRITE_B': 'machine stats', 'TOTAL_L1_READ_B': 'machine stats', 'TOTAL_L1_WRITE_B': 'machine stats', 'L2_READ_B_XECORE_CLK': 'machine stats', 'L2_WRITE_B_XECORE_CLK': 'machine stats', 'L2_READ_WRITE_B_XECORE_CLK': 'machine stats', 'L1_READ_B_XECORE_CLK': 'machine stats', 'L1_WRITE_B_XECORECLK': 'machine stats', 'L1_READ_B_EU_CLK': 'machine stats', 'L1_WRITE_B_EU_CLK': 'machine stats', 'L2_READ_MAX_B_XECORE_CLK': 'machine stats', 'L2_WRITE_MAX_B_XECORE_CLK': 'machine stats', 'L2_READ_WRITE_MAX_B_XECORE_CLK': 'machine stats', 'L1_READ_MAX_B_EU_CLK': 'machine pre', 'L1_WRITE_MAX_B_EU_CLK': 'machine pre', 'L2_READ_B_XECORE_CLK_PCT': 'machine stats', 'L2_WRITE_B_XECORE_CLK_PCT': 'machine stats', 'L2_READ_WRITE_B_XECORE_CLK_PCT': 'machine stats', 'L1_READ_B_EU_CLK_PCT': 'machine stats', 'L1_WRITE_B_EU_CLK_PCT': 'machine stats', 'GTI_READ_MAX_BW_B_CLK': 'machine pre', 'GTI_WRITE_MAX_BW_B_CLK': 'machine pre', 'TOTAL_L2_SIZE_B_FOR_A_SINGLE_INSTANCE': 'machine derived', 'WORKING_DATA_SET_SIZE_OF_K_IN_L2_CORRESP_20K_CLOCKS_OF_THREAD_DIVERGENCE': 'workload derived', 'TOTAL_REQUIRED_L2_SIZE_FOR_IDEAL_HIT_RATE_B_FOR_A_SINGLE_INSTANCE_AND_SINGLE_WAVE': 'workload derived', 'L2_HIT_RATE_ASSUMED_RANDOM_ACCESS_WITHIN_THE_WORKING_DATA_SET_PCT': 'machine stats', 'L2_MISS_RATE_PCT': 'machine stats', 'TOTAL_L2_READ_TRAFFIC_B': 'machine stats', 'PROBABILITY_OF_MATA_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': 'machine stats', 'PROBABILITY_OF_MATB_HIT_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': 'machine stats', 'PROBABILITY_OF_MATA_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': 'machine stats', 'PROBABILITY_OF_MATB_MISS_IN_L2_DURING_A_NON_FIRST_WAVE_PCT': 'machine stats', 'TOTAL_HBM_READ_B_AFTER_A_COMPLETION_OF_A_WAVE_CONSIDER_COLD_CACHE': 'machine stats', 'TOTAL_HBM_WRITE_B': 'machine stats', 'TOTAL_HBM_B': 'machine stats', 'HBM_READ_B_CLK': 'machine stats', 'HBM_WRITE_B_CLK': 'machine stats', 'HBM_TOTAL_B_CLK': 'machine stats', 'MAX_POSSIBLE_HBM_BW_GB_S': 'machine pre', 'MAX_POSSIBLE_HBM_BW_FREQ_B_CLK': 'machine derived', 'HBM_BW_PCT': 'machine stats', 'GTI_READ_BW_PCT': 'machine stats', 'GTI_WRITE_BW_PCT': 'machine stats'}

def format_value_for_report(name: str, value):
    if name in PERCENT_NAMES and isinstance(value, (int, float)):
        return format(value, '.2%')
    return value

def _resolve_output_order(output_order: str) -> str:
    """Normalize output-order values to internal order keys.

    Returns:
        'compute' for execution order or 'xlsx' for row-tracking order.
    """
    if output_order == 'execution':
        return 'compute'
    if output_order == 'row_tracking':
        return 'xlsx'
    raise ValueError(f'Unsupported output order: {output_order}')


def build_normal_report(values: dict, output_order: str = 'execution') -> str:
    """Build normal report with structure matching output_order.
    
    Args:
        values: dict of computed values
        output_order: 'execution' for 4-section compute flow, 'row_tracking' for 5-section domain structure
    """
    internal_order = _resolve_output_order(output_order)
    item_order = COMPUTE_ORDER if internal_order == 'compute' else ROW_ORDER
    out: list[str] = []
    out.append(f'Source: {SOURCE_XLSX}  Sheet: {SOURCE_SHEET}')
    out.append('')
    out.append('--- NORMAL MODE ---')
    out.append('')
    
    if internal_order == 'compute':
        # 4-section structure following compute execution order
        out.append('[1] MACHINE PARAMETERS (PRE-DEFINED)')
        for name in item_order:
            if name in MACHINE_PRE_NAMES:
                if name in values:
                    val = format_value_for_report(name, values[name])
                    out.append(f'  {name} = {val}')
        out.append('')
        
        out.append('[2] WORKLOAD PARAMETERS (PRE-DEFINED)')
        for name in item_order:
            if name in FORMAT_KEY_NAMES or name in WORKLOAD_PRE_NAMES:
                if name in values:
                    val = format_value_for_report(name, values[name])
                    out.append(f'  {name} = {val}')
        out.append('')
        
        out.append('[3] DERIVED PARAMETERS')
        for name in item_order:
            if name in (WORKLOAD_FMT_VAL_NAMES + MACHINE_DERIVED_NAMES + MACHINE_WL_DERIVED_NAMES + WORKLOAD_DERIVED_NAMES):
                if name in values:
                    val = format_value_for_report(name, values[name])
                    out.append(f'  {name} = {val}')
        out.append('')
        
        out.append('[4] MACHINE STATS')
        for name in item_order:
            if name in MACHINE_STATS_NAMES:
                if name in values:
                    val = format_value_for_report(name, values[name])
                    out.append(f'  {name} = {val}')
    else:
        # 5-section structure organized by domain and type (row_tracking)
        out.append('[1] WORKLOAD PARAMETERS (PRE-DEFINED)')
        for name in item_order:
            if name in FORMAT_KEY_NAMES or name in WORKLOAD_PRE_NAMES:
                if name in values:
                    val = format_value_for_report(name, values[name])
                    out.append(f'  {name} = {val}')
        out.append('')
        out.append('[2] WORKLOAD PARAMETERS (DERIVED)')
        for name in item_order:
            if name in WORKLOAD_FMT_VAL_NAMES or name in WORKLOAD_DERIVED_NAMES:
                if name in values:
                    val = format_value_for_report(name, values[name])
                    out.append(f'  {name} = {val}')
        out.append('')
        out.append('[3] MACHINE PARAMETERS (PRE-DEFINED)')
        for name in item_order:
            if name in MACHINE_PRE_NAMES:
                if name in values:
                    val = format_value_for_report(name, values[name])
                    out.append(f'  {name} = {val}')
        out.append('')
        out.append('[4] MACHINE PARAMETERS (DERIVED)')
        for name in item_order:
            if name in MACHINE_DERIVED_NAMES or name in MACHINE_WL_DERIVED_NAMES:
                if name in values:
                    val = format_value_for_report(name, values[name])
                    out.append(f'  {name} = {val}')
        out.append('')
        out.append('[5] MACHINE STATS')
        for name in item_order:
            if name in MACHINE_STATS_NAMES:
                if name in values:
                    val = format_value_for_report(name, values[name])
                    out.append(f'  {name} = {val}')
    out.append('')
    return '\n'.join(out)

def build_debug_report(values: dict) -> str:
    out: list[str] = []
    out.append(f'Source: {SOURCE_XLSX}  Sheet: {SOURCE_SHEET}')
    out.append('')
    out.append('--- DEBUG MODE (ORIGINAL XLSX ROW ORDER) ---')
    for name in ROW_ORDER:
        if name not in values:
            continue
        row = ROW_INDEX.get(name, '?')
        cat = CATEGORY_MAP.get(name, '')
        display_name = f'{name}_C{row}'
        val = format_value_for_report(name, values[name])
        if name in FORMAT_KEY_NAMES or name in WORKLOAD_PRE_NAMES or name in MACHINE_PRE_NAMES:
            out.append(f'  row {row} [{cat}]: {display_name} = {val}')
        else:
            formula = PYTHON_FORMULAS.get(name, '')
            out.append(f'  row {row} [{cat}]: {display_name}')
            out.append(f'    formula : {formula}')
            out.append(f'    result  : {val}')
    out.append('')
    return '\n'.join(out)

def export_to_csv(values: dict, csv_path: str, output_order: str = 'execution') -> None:
    """Export model values to CSV with metadata (Name, Value, Category, Row, Label).
    
    Args:
        values: dict of computed values
        csv_path: output CSV file path
        output_order: 'execution' for compute order (default), 'row_tracking' for xlsx row order
    """
    internal_order = _resolve_output_order(output_order)
    item_order = COMPUTE_ORDER if internal_order == 'compute' else ROW_ORDER
    with open(csv_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['Name', 'Value', 'Category', 'Row', 'Label'])
        for name in item_order:
            if name not in values:
                continue
            writer.writerow([name, values[name], CATEGORY_MAP.get(name, ''), ROW_INDEX.get(name, ''), ''])

def parse_cli_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description='Run GEMM model with workload and machine parameters.')
    parser.add_argument('--workload-params', required=True, metavar='CSV', help='Workload parameters CSV (Name,Value[,Label])')
    parser.add_argument('--machine-params', required=True, metavar='CSV', help='Machine parameters CSV (Name,Value[,Label])')
    parser.add_argument('--mode', choices=['normal', 'debug'], default='normal', help='normal: 5-section summary; debug: row-order detail with formulas')
    parser.add_argument('--output-order', choices=['execution', 'row_tracking'], default='execution', help="output order: 'execution' for 4-section compute order (default), 'row_tracking' for original xlsx row order")
    parser.add_argument('--output-txt', default=None, help='(Optional) also write text report to file')
    parser.add_argument('--output-csv', default=None, help='(Optional) also export model values to CSV')
    parser.add_argument('--output-equations-md', default=None, metavar='MD', help='(Optional) export equations markdown using LaTeX symbol mapping')
    parser.add_argument('--no-stdout', action='store_true', help='Suppress stdout output')
    return parser.parse_args()

def main() -> None:
    args = parse_cli_args()
    workload_params = _load_params_csv(args.workload_params, ALL_WORKLOAD_PRE_NAMES, 'workload', ALL_PRE_NAMES_SET)
    machine_params  = _load_params_csv(args.machine_params,  MACHINE_PRE_NAMES,       'machine',  ALL_PRE_NAMES_SET)
    values = compute_core_values(workload_params, machine_params)
    report = build_debug_report(values) if args.mode == 'debug' else build_normal_report(values, output_order=args.output_order)
    if not args.no_stdout:
        print(report)
    if args.output_txt:
        with open(args.output_txt, 'w', encoding='utf-8') as f:
            f.write(report)
    if args.output_csv:
        export_to_csv(values, args.output_csv, output_order=args.output_order)
    if args.output_equations_md:
        export_equations_markdown(args.output_equations_md, output_order=args.output_order)

if __name__ == '__main__':
    main()
